### ISSUE TITLE
Utilize importTransactions instead of createTransactions

### ISSUE THREAD

**Issue by tm1000** [TinyAnvil/applecardforynab-serverless#4]
Utilize importTransactions instead of createTransactions. The reasoning is because if you are manually adding transactions before you send the email off with the csv when you actually send the email all transactions will be duplicated whereas with importTransactions they will be linked if the dates and amounts are equal

**Comment by tyvdh** [comment]
The `importTransactions` endpoint doesn't make sense to me. It doesn't seem to take a list of new transactions as an argument. If however I include `import_id`'s on the list of created transactions the desired result is achieved. I have made and published that update. Good catch!

**Comment by tm1000** [comment]
@tyvdh i looked over the commit and also the reference model and I agree with you. Only question I have is that you set one of the parts to now instead of the date of the transaction. Shouldn't that be changed to the date of the transaction? Or does it not matter in the end?

**Comment by tyvdh** [comment]
In my opinion it should be set to the date of the import (`now`) rather than the date of the transaction. That's how YNAB does it for imports in their UI and it makes sense to me. Ultimately I don't think it really matters that much though unless maybe you sent the email with the CSV more than once. In that case it would import duplicates but that's likely the scenario you want as I don't know how YNAB handles deletions or transaction modifications and if you royally screw up your import you could just reimport and start over vs potentially just reimporting over the same transactions and having them be skipped. Again not sure that would be the case but these seems to be the right route.

**Comment by tm1000** [comment]
@tyvdh after using your changes for the last two statements it's working great and everything is linking. Thank you!
